import Mathlib.Probability.Independence.Basic

/-!
# Independence groups over disjoint blocks

Mathlib has the two-block case (`indep_iSup_of_disjoint`): the σ-algebras generated by two
disjoint sub-families of an independent family are independent.  The proof here is the
`n`-block version, which is what a family of statistics — each reading its own block of an
independent family — needs.

The π-system for a block is the finite intersections over it, and the independence of those
is the original family's independence read along the union of the blocks.
-/

namespace OrthoDFA

open MeasureTheory ProbabilityTheory MeasurableSpace Set

variable {Ω ι κ : Type*} [mΩ : MeasurableSpace Ω] {μ : Measure Ω}

open scoped Classical in
/-- The finite intersections over one block — a π-system generating the block's σ-algebra. -/
def blockPi (m : κ → MeasurableSpace Ω) (A : Finset κ) : Set (Set Ω) :=
  {s | ∃ f : κ → Set Ω, (∀ w ∈ A, MeasurableSet[m w] (f w)) ∧ s = ⋂ w ∈ A, f w}

lemma isPiSystem_blockPi (m : κ → MeasurableSpace Ω) (A : Finset κ) :
    IsPiSystem (blockPi m A) := by
  rintro s ⟨f, hf, rfl⟩ t ⟨g, hg, rfl⟩ -
  refine ⟨fun w => f w ∩ g w, fun w hw => (hf w hw).inter (hg w hw), ?_⟩
  ext ω
  simp only [Set.mem_inter_iff, Set.mem_iInter]
  exact ⟨fun h w hw => ⟨h.1 w hw, h.2 w hw⟩,
    fun h => ⟨fun w hw => (h w hw).1, fun w hw => (h w hw).2⟩⟩

lemma mem_blockPi_of_mem (m : κ → MeasurableSpace Ω) {A : Finset κ} {w : κ} (hw : w ∈ A)
    {s : Set Ω} (hs : MeasurableSet[m w] s) : s ∈ blockPi m A := by
  classical
  refine ⟨fun w' => if w' = w then s else Set.univ, fun w' _ => ?_, ?_⟩
  · show MeasurableSet[m w'] (if w' = w then s else Set.univ)
    split_ifs with h
    · exact h ▸ hs
    · exact MeasurableSet.univ
  · ext ω
    simp only [Set.mem_iInter]
    constructor
    · intro hωs w' _
      split_ifs
      · exact hωs
      · trivial
    · intro hall
      simpa using hall w hw

lemma generateFrom_blockPi (m : κ → MeasurableSpace Ω) (A : Finset κ) :
    generateFrom (blockPi m A) = ⨆ w ∈ A, m w := by
  refine le_antisymm (generateFrom_le ?_) (iSup₂_le fun w hw => ?_)
  · rintro s ⟨f, hf, rfl⟩
    refine Finset.measurableSet_biInter A (fun w hw => ?_)
    exact le_iSup₂ (f := fun w (_ : w ∈ A) => m w) w hw _ (hf w hw)
  · intro s hs
    exact measurableSet_generateFrom (mem_blockPi_of_mem m hw hs)

open scoped Classical in
/-- **The grouping lemma.**  Blocks of an independent family generate independent
σ-algebras. -/
theorem iIndep_biSup_of_disjoint {m : κ → MeasurableSpace Ω} (hle : ∀ w, m w ≤ mΩ)
    (hindep : iIndep m μ) (A : ι → Finset κ)
    (hdisj : Pairwise (fun i j => Disjoint (A i) (A j))) :
    iIndep (fun i => ⨆ w ∈ A i, m w) μ := by
  classical
  refine iIndepSets.iIndep (fun i => iSup₂_le fun w _ => hle w)
    (fun i => blockPi m (A i)) (fun i => isPiSystem_blockPi m (A i))
    (fun i => (generateFrom_blockPi m (A i)).symm) ?_
  rw [iIndepSets_iff]
  intro S f hf
  choose g hgm hgeq using fun i (hi : i ∈ S) => hf i hi
  -- the block sets, spread over the union of the blocks
  set T : Finset κ := S.biUnion A with hT
  set h : κ → Set Ω := fun w => ⋂ i ∈ S.filter (fun i => w ∈ A i),
    (if hi : i ∈ S then g i hi w else Set.univ) with hh
  have hhmeas : ∀ w ∈ T, MeasurableSet[m w] (h w) := by
    intro w _
    refine Finset.measurableSet_biInter _ (fun i hi => ?_)
    obtain ⟨hiS, hwA⟩ := Finset.mem_filter.1 hi
    rw [dif_pos hiS]
    exact hgm i hiS w hwA
  have hblock : ∀ (i : ι) (hi : i ∈ S), ∀ w ∈ A i, h w = g i hi w := by
    intro i hi w hw
    have hfilter : S.filter (fun i' => w ∈ A i') = {i} := by
      refine Finset.eq_singleton_iff_unique_mem.2 ⟨Finset.mem_filter.2 ⟨hi, hw⟩, fun j hj => ?_⟩
      obtain ⟨hjS, hwj⟩ := Finset.mem_filter.1 hj
      by_contra hne
      exact (Finset.disjoint_left.1 (hdisj hne) hwj) hw
    rw [hh]
    simp only [hfilter, Finset.mem_singleton, Set.iInter_iInter_eq_left, dif_pos hi]
  have hinter : (⋂ i ∈ S, f i) = ⋂ w ∈ T, h w := by
    ext ω
    simp only [Set.mem_iInter]
    constructor
    · intro hω w hw
      obtain ⟨i, hiS, hwA⟩ := Finset.mem_biUnion.1 hw
      rw [hblock i hiS w hwA]
      have := hω i hiS
      rw [hgeq i hiS] at this
      simpa using (Set.mem_iInter₂.1 this) w hwA
    · intro hω i hiS
      rw [hgeq i hiS]
      refine Set.mem_iInter₂.2 (fun w hw => ?_)
      have := hω w (Finset.mem_biUnion.2 ⟨i, hiS, hw⟩)
      rwa [hblock i hiS w hw] at this
  have hprod : ∀ i ∈ S, μ (f i) = ∏ w ∈ A i, μ (h w) := by
    intro i hiS
    rw [hgeq i hiS]
    rw [show (⋂ w ∈ A i, g i hiS w) = ⋂ w ∈ A i, h w from by
      refine Set.iInter₂_congr (fun w hw => ?_)
      rw [hblock i hiS w hw]]
    exact hindep.meas_biInter (fun w hw => hhmeas w (Finset.mem_biUnion.2 ⟨i, hiS, hw⟩))
  rw [hinter, hindep.meas_biInter hhmeas, hT,
    Finset.prod_biUnion (fun i hi j hj hij => hdisj hij)]
  exact (Finset.prod_congr rfl (fun i hi => hprod i hi)).symm

/-- **Functions of disjoint blocks are independent.**  The statistics each read their own
block of an independent family, so the σ-algebras they generate sit inside independent
ones. -/
theorem iIndepFun_blocks {X : κ → Ω → ℝ} (hX : ∀ w, Measurable (X w))
    (hindep : iIndepFun X μ) (A : ι → Finset κ)
    (hdisj : Pairwise (fun i j => Disjoint (A i) (A j))) (g : ι → Ω → ℝ)
    (hgmeas : ∀ i, Measurable[⨆ w ∈ A i, MeasurableSpace.comap (X w) inferInstance] (g i)) :
    iIndepFun g μ := by
  have hle : ∀ w, MeasurableSpace.comap (X w) (inferInstance : MeasurableSpace ℝ) ≤ mΩ :=
    fun w => (hX w).comap_le
  have hgroup := iIndep_biSup_of_disjoint hle
    ((iIndepFun_iff_iIndep (fun _ => (inferInstance : MeasurableSpace ℝ)) X μ).1 hindep) A hdisj
  refine (iIndepFun_iff_iIndep (fun _ => (inferInstance : MeasurableSpace ℝ)) g μ).2 ?_
  refine iIndep_of_iIndep_of_le hgroup (fun i => ?_)
  exact (hgmeas i).comap_le

end OrthoDFA
